# -*- coding: utf-8 -*-
'''17 篇真题套用示范的「手工挑句组 + 真题真实数据」方案（2026-09-15 起）。

为什么要有这个文件
  v2 的示范文由 `auto_compose` 自动选句、槽位里塞的是「a modest share」这类文字而非数字，
  结果出现四类硬伤：① 全文没有真实数字；② 主谓不一致（brands has moved）；
  ③ 逻辑矛盾（fell → 更大的份额）；④ 数据重复 + 多选型图表算「合计」。
  这里改为**人工挑句组 + 真实数据**：每一年由人指定用哪几句（refs）、填什么数字。

字段
  ch / chcn          图型（bar / pie / line / table）
  topic / topiccn    P1 的主题名词（P2、P3 若要换措辞，用 topic2 / topic3）
  multi              1 = 多选题（各项占比之和 > 100%，**禁用「合计」类句子**）
  p1 / p2 / p3       (section_id, refs)；refs 形如 't1 t2 f4'（t=骨架句，f=功能句，均 1 起）
  s / scn            槽位值（en / cn）；`s` 同时用于 P1，P2/P3 只另给 topic

数据来源：`pwa/data/{year}.json` 的 `sample_en`（参考答案范文，含图表数字）+ 真题原图
         `pwa/img/{year}_writingb_chart.png`（参考答案未写全数字的年份逐张核对）。
'''

CHART = {
    '2010': dict(ch='bar', chcn='柱状', multi=0,
                 topic='mobile-phone subscriptions', topiccn='手机用户数',
                 s={'item1': 'those in developing countries', 'num1': '0.5 billion', 'num2': '4 billion',
                    'item2': 'those in developed countries', 'num3': '0.7 billion', 'num4': '1 billion',
                    'time1': '2000', 'time2': '2008'},
                 scn={'item1': '发展中国家', 'num1': '5 亿', 'num2': '40 亿',
                      'item2': '发达国家', 'num3': '7 亿', 'num4': '10 亿',
                      'time1': '2000 年', 'time2': '2008 年'},
                 p1=('chart_dynamic', 't1 t2 f:同向不同速 f:差距'),
                 p2=('para2_why', 't1 f:收入 f:便利 f:观念'),
                 p3=('para3_positive', 't1 f:政府 f:观念 t2'),
                 topic2='mobile phone use', topic2cn='手机的使用',
                 topic3='mobile phone use', topic3cn='手机的使用',
                 pl=[]),

    '2011': dict(ch='bar', chcn='柱状', multi=0,
                 topic='the market shares of Chinese, Japanese and American car brands',
                 topiccn='国产、日系与美系汽车品牌的市场份额',
                 s={'item1': 'Chinese brands', 'num1': '26%', 'num2': '31%',
                    'item2': 'Japanese brands', 'num3': '35%', 'num4': '26%',
                    'time1': '2008', 'time2': '2009'},
                 scn={'item1': '国产品牌', 'num1': '26%', 'num2': '31%',
                      'item2': '日系品牌', 'num3': '35%', 'num4': '26%',
                      'time1': '2008 年', 'time2': '2009 年'},
                 p1=('chart_dynamic', 't1 t2 f:反差 f:差距'),
                 p2=(('para2_why', 't1 f:观念 f:公共投入 f:国产替代 f:城市化')),
                 p3=('para3_positive', 't1 f:企业/平台 f:政府·长效 t2'),
                 topic2='car ownership', topic2cn='汽车保有量',
                 topic3='domestic car brands', topic3cn='国产汽车品牌',
                 pl=['domestic car brands']),

    '2012': dict(ch='table', chcn='表格', multi=0,
                 topic='employee dissatisfaction', topiccn='员工的不满意比例',
                 s={'item1': 'the 41-to-50 age group', 'percent1': '64%',
                    'item2': 'those aged 40 or younger', 'percent2': '33.3%',
                    'item3': 'the group over 50', 'percent3': '10%'},
                 scn={'item1': '41~50 岁组', 'percent1': '64%',
                      'item2': '40 岁及以下组', 'percent2': '33.3%',
                      'item3': '50 岁以上组', 'percent3': '10%'},
                 p1=('chart_static', 't1 t2 t3 f:差距 f:集中度'),
                 p2=('para2_why', 't1 f:职场时间 f:职场流动 f:观念'),
                 p3=('para3_negative', 't1 f:企业·雇主 f:企业·管理 t2'),
                 topic2='job satisfaction', topic2cn='工作满意度',
                 topic3='staff satisfaction', topic3cn='员工满意度',
                 pl=[]),

    '2013': dict(ch='bar', chcn='柱状', multi=0,
                 topic='the proportion of college students taking part-time jobs',
                 topiccn='大学生兼职比例',
                 s={'item1': 'the proportion of college students taking part-time jobs',
                    'num1': '67.77%', 'num2': '88.24%',
                    'time1': 'the first year', 'time2': 'the final year', 'time3': 'the third year', 'num3': '71.93%'},
                 scn={'item1': '大学生兼职比例', 'num1': '67.77%', 'num2': '88.24%',
                      'time1': '大一', 'time2': '大四'},
                 p1=('chart_dynamic', 't1 t2 f:加速'),
                 p2=('para2_why', 't1 f:学校 f:就业门槛 f:观念 f:职场流动'),
                 p3=('para3_positive', 't1 f:学校 f:家庭 t2'),
                 topic2='part-time work', topic2cn='兼职',
                 topic3='part-time work', topic3cn='兼职',
                 pl=[]),

    '2014': dict(ch='bar', chcn='柱状', multi=0,
                 topic='the urban and rural population', topiccn='城乡人口',
                 s={'item1': 'the urban population', 'num1': '300 million', 'num2': '666 million',
                    'item2': 'the rural population', 'num3': '834 million', 'num4': '674 million',
                    'time1': '1990', 'time2': '2010'},
                 scn={'item1': '城镇人口', 'num1': '3 亿', 'num2': '6.66 亿',
                      'item2': '乡村人口', 'num3': '8.34 亿', 'num4': '6.74 亿',
                      'time1': '1990 年', 'time2': '2010 年'},
                 p1=('chart_dynamic', 't1 t2 f:反差 f:差距'),
                 p2=(('para2_why', 't1 f:城市化 f:收入 f:公共投入 f:观念')),
                 p3=(('para3_positive', 't1 f:政府 f:政府·长效 f:观念 t2')),
                 topic2='city living', topic2cn='城市生活',
                 topic3='city living', topic3cn='城市生活',
                 pl=[]),

    '2015': dict(ch='pie', chcn='饼状', multi=0,
                 topic='Spring Festival spending', topiccn='春节假期花销',
                 s={'item1': 'gifts for family and friends', 'percent1': '40%',
                    'item2': 'dinners with relatives', 'percent2': '20%',
                    'item3': 'transportation', 'percent3': '20%',
                    'item4': 'other spending', 'percent4': '20%', 'percent total': '80%'},
                 scn={'item1': '给亲友买礼物', 'percent1': '40%',
                      'item2': '与亲友聚餐', 'percent2': '20%',
                      'item3': '出行', 'percent3': '20%',
                      'item4': '其他花销', 'percent4': '20%', 'percent total': '80%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:合计'),
                 p2=(('para2_why', 't1 f:收入 f:观念 f:便利 f:文化传承')),
                 p3=('para3_positive', 't1 f:个人 f:观念 t2'),
                 topic2='New Year gifts', topic2cn='新年礼物',
                 topic3='festival spending', topic3cn='节日花销',
                 pl=['gifts for family and friends', 'New Year gifts']),

    '2016': dict(ch='pie', chcn='饼状', multi=0,
                 topic='the purposes of travel', topiccn='旅游目的',
                 s={'item1': 'appreciating the scenery', 'percent1': '37%',
                     'item2': 'relieving pressure', 'percent2': '33%',
                     'item3': 'other aims', 'percent3': '15%',
                     'item4': 'fostering independence', 'percent4': '6%',
                     'percent total': '85%'},
                 scn={'item1': '欣赏风景', 'percent1': '37%',
                      'item2': '缓解压力', 'percent2': '33%',
                      'item3': '其他目的', 'percent3': '15%',
                      'item4': '锻炼独立性', 'percent4': '6%',
                      'percent total': '85%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:合计'),
                 p2=(('para2_why', 't1 f:收入 f:职场时间 f:便利 f:公共投入')),
                 p3=(('para3_positive', 't1 f:媒体 f:个人 f:观念 t2')),
                 topic2='travelling', topic2cn='旅游',
                 topic3='travelling', topic3cn='旅游',
                 pl=['the purposes of travel']),

    '2017': dict(ch='line', chcn='折线', multi=0,
                 topic='the number of museums and museum visitors', topiccn='博物馆数量与参观人数',
                 s={'item1': 'visitor numbers', 'num1': '640 million', 'num2': '780 million',
                    'item2': 'the number of museums', 'num3': '4,200', 'num4': '4,600',
                    'time1': '2013', 'time2': '2015'},
                 scn={'item1': '参观人数', 'num1': '6.4 亿', 'num2': '7.8 亿',
                      'item2': '博物馆数量', 'num3': '4200 家', 'num4': '4600 家',
                      'time1': '2013 年', 'time2': '2015 年'},
                 p1=('chart_dynamic', 't1 t2 f:差距'),
                 p2=('para2_why', 't1 f:公共投入 f:学校 f:文化传承 f:观念'),
                 p3=('para3_positive', 't1 f:政府 f:媒体·展示 t2'),
                 topic2='museum visiting', topic2cn='参观博物馆',
                 topic3='museum visiting', topic3cn='参观博物馆',
                 pl=[]),

    '2018': dict(ch='pie', chcn='饼状', multi=0,
                 topic='the factors consumers weigh when choosing a restaurant',
                 topiccn='消费者选择餐厅时考虑的因素',
                 s={'item1': 'distinctive features', 'percent1': '36.3%',
                    'item2': 'service', 'percent2': '26.8%',
                    'item3': 'the dining environment', 'percent3': '23.8%',
                    'item4': 'other factors', 'percent4': '4.7%',
                    'percent total': '86.9%'},
                 scn={'item1': '餐厅特色', 'percent1': '36.3%',
                      'item2': '服务', 'percent2': '26.8%',
                      'item3': '就餐环境', 'percent3': '23.8%',
                      'item4': '其他因素', 'percent4': '4.7%',
                      'percent total': '86.9%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:合计'),
                 p2=('para2_why', 't1 f:收入 f:观念 f:便利'),
                 p3=(('para3_positive', 't1 f:企业/平台 f:平台·设计 f:个人 t2')),
                 topic2='dining out', topic2cn='外出就餐',
                 topic3='dining out', topic3cn='外出就餐',
                 pl=['the factors consumers weigh when choosing a restaurant', 'distinctive features', 'other factors']),

    '2019': dict(ch='bar', chcn='柱状', multi=0,
                 topic="graduates' destinations", topiccn='毕业生去向',
                 s={'item1': 'the share going on to further study', 'num1': '26.3%', 'num2': '34.0%',
                    'item2': 'the share entering employment', 'num3': '68.1%', 'num4': '60.7%',
                    'time1': '2013', 'time2': '2018'},
                 scn={'item1': '升学比例', 'num1': '26.3%', 'num2': '34.0%',
                      'item2': '就业比例', 'num3': '68.1%', 'num4': '60.7%',
                      'time1': '2013 年', 'time2': '2018 年'},
                 p1=('chart_dynamic', 't1 t2 f:反差 f:差距'),
                 p2=('para2_why', 't1 f:就业门槛 f:学校 f:观念 f:职场流动'),
                 p3=('para3_positive', 't1 f:学校 f:观念 t2'),
                 topic2='career planning', topic2cn='职业规划',
                 topic3='career planning', topic3cn='职业规划',
                 pl=[]),

    '2020': dict(ch='pie', chcn='饼状', multi=0,
                 topic='the purposes of mobile reading', topiccn='手机阅读目的',
                 s={'item1': 'reading for knowledge', 'percent1': '59.5%',
                    'item2': 'killing time', 'percent2': '21.3%',
                    'item3': 'obtaining information', 'percent3': '17.0%',
                    'item4': 'other purposes', 'percent4': '2.2%',
                    'percent total': '97.8%'},
                 scn={'item1': '获取知识', 'percent1': '59.5%',
                      'item2': '消磨时间', 'percent2': '21.3%',
                      'item3': '获取信息', 'percent3': '17.0%',
                      'item4': '其他目的', 'percent4': '2.2%',
                      'percent total': '97.8%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:合计'),
                 p2=('para2_why', 't1 f:便利 f:职场时间 f:观念'),
                 p3=(('para3_positive', 't1 f:媒体 f:平台·设计 f:个人·习惯 t2')),
                 topic2='mobile reading', topic2cn='手机阅读',
                 topic3='mobile reading', topic3cn='手机阅读',
                 pl=['the purposes of mobile reading', 'other purposes']),

    '2021': dict(ch='bar', chcn='柱状', multi=1,
                 topic='the ways residents take exercise', topiccn='居民的锻炼方式',
                 s={'item1': "exercising on one's own", 'percent1': '54.3%',
                    'item2': 'exercising with friends', 'percent2': '47.7%',
                    'item3': 'exercising with family', 'percent3': '23.9%',
                    'item4': 'team sports', 'percent4': '15.8%'},
                 scn={'item1': '独自锻炼', 'percent1': '54.3%',
                      'item2': '与朋友一起', 'percent2': '47.7%',
                      'item3': '与家人一起', 'percent3': '23.9%',
                      'item4': '团队项目', 'percent4': '16%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:差距'),
                 p2=('para2_why', 't1 f:久坐 f:职场时间 f:公共投入 f:观念'),
                 p3=('para3_positive', 't1 f:个人 f:个人·习惯 f:观念 t2'),
                 topic2='exercising', topic2cn='锻炼',
                 topic3='exercise', topic3cn='运动',
                 pl=['the ways residents take exercise', 'team sports']),

    '2022': dict(ch='bar', chcn='柱状', multi=0,
                 topic='express delivery volume', topiccn='快递业务量',
                 s={'item1': 'the rural figure', 'num1': '12 billion pieces', 'num2': '30 billion pieces',
                    'item2': 'the national total', 'num3': '51 billion pieces', 'num4': '83 billion pieces',
                    'time1': '2018', 'time2': '2020'},
                 scn={'item1': '农村快递量', 'num1': '120 亿件', 'num2': '300 亿件',
                      'item2': '全国总量', 'num3': '510 亿件', 'num4': '830 亿件',
                      'time1': '2018 年', 'time2': '2020 年'},
                 p1=('chart_dynamic', 't1 t2 f:差距 f:加速'),
                 p2=('para2_why', 't1 f:成本 f:便利 f:城市化'),
                 p3=('para3_positive', 't1 f:政府 f:企业/平台 t2'),
                 topic2='online shopping', topic2cn='网购',
                 topic3='online shopping', topic3cn='网购',
                 pl=[]),

    '2023': dict(ch='line', chcn='折线', multi=0,
                 topic='the health literacy rate of Chinese residents', topiccn='居民健康素养水平',
                 s={'item1': 'the health literacy rate of Chinese residents',
                    'num1': '8.80%', 'num2': '25.40%', 'time1': '2012', 'time2': '2021', 'time3': '2015', 'num3': '10.25%'},
                 scn={'item1': '居民健康素养水平', 'num1': '8.80%', 'num2': '25.40%',
                      'time1': '2012 年', 'time2': '2021 年'},
                 p1=('chart_dynamic', 't1 t2 f:加速 f:倍数'),
                 p2=('para2_why', 't1 f:公共投入 f:观念 f:久坐 f:学校'),
                 p3=(('para3_positive', 't1 f:媒体 f:政府·长效 f:个人 t2')),
                 topic2='health literacy', topic2cn='健康素养',
                 topic3='health literacy', topic3cn='健康素养',
                 pl=[]),

    '2024': dict(ch='bar', chcn='柱状', multi=1,
                 topic='labour practice course gains',
                 topiccn='劳动实践课的收获',
                 s={'item1': 'gaining relevant knowledge', 'percent1': '91.3%',
                    'item2': 'improving practical ability', 'percent2': '84.8%',
                    'item3': 'obtaining cheerful moods', 'percent3': '54.4%',
                    'item4': 'enhancing cooperative ability', 'percent4': '32.6%'},
                 scn={'item1': '获得相关知识', 'percent1': '91.3%',
                      'item2': '提高实践能力', 'percent2': '84.8%',
                      'item3': '获得愉悦心情', 'percent3': '54.4%',
                      'item4': '增强合作能力', 'percent4': '32.6%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:差距'),
                 p2=('para2_why', 't1 f:学校 f:就业门槛 f:观念 f:职场流动'),
                 p3=('para3_positive', 't1 f:学校 f:观念 t2'),
                 topic2='labour practice courses', topic2cn='劳动实践课',
                 topic3='practical training', topic3cn='实践训练',
                 pl=['labour practice course gains', 'labour practice courses']),

    '2025': dict(ch='bar', chcn='柱状', multi=1,
                 topic='the leisure activities of the elderly', topiccn='老年人的休闲活动',
                 s={'item1': 'watching television', 'percent1': '90.8%',
                    'item2': 'taking walks', 'percent2': '68.3%',
                    'item3': 'planting flowers', 'percent3': '34.7%',
                    'item4': 'playing chess', 'percent4': '18.4%'},
                 scn={'item1': '看电视', 'percent1': '90.8%',
                      'item2': '散步', 'percent2': '68.3%',
                      'item3': '种花', 'percent3': '34.7%',
                      'item4': '下棋', 'percent4': '18.4%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:差距'),
                 p2=('para2_why', 't1 f:人口结构 f:收入 f:观念 f:公共投入'),
                 p3=('para3_positive', 't1 f:政府·长效 f:个人·习惯 f:观念 t2'),
                 topic2='retirement life', topic2cn='退休生活',
                 topic3='leisure activity', topic3cn='休闲活动',
                 pl=['the leisure activities of the elderly']),

    '2026': dict(ch='bar', chcn='柱状', multi=1,
                 topic='the perceived benefits of outdoor activities for children',
                 topiccn='儿童户外活动的益处',
                 s={'item1': 'satisfying curiosity', 'percent1': '54.6%',
                    'item2': 'improving observation skills', 'percent2': '54.5%',
                    'item3': 'enhancing physical fitness', 'percent3': '33.2%',
                    'item4': 'strengthening parent-child interaction', 'percent4': '31.2%'},
                 scn={'item1': '满足好奇心', 'percent1': '54.6%',
                      'item2': '促进观察力', 'percent2': '54.5%',
                      'item3': '强身健体', 'percent3': '33.2%',
                      'item4': '增强亲子互动', 'percent4': '31.2%'},
                 p1=('chart_static', 't1 t2 t3 t4 f:差距'),
                 p2=('para2_why', 't1 f:久坐 f:公共投入 f:观念 f:学校'),
                 p3=('para3_positive', 't1 f:家庭 f:学校 t2'),
                 topic2='outdoor activity', topic2cn='户外活动',
                 topic3='outdoor activity', topic3cn='户外活动',
                 pl=['the perceived benefits of outdoor activities for children']),
}

# 新增句池句子（写进 writing_templates.json；按 idempotent 方式插入，顺序即下文顺序）
# 句池已在 rebuild_skeleton.py 里整体重建（2026-09-16），这里不再补句
NEW_POOL = {}

# 动态骨架 ② 的首句原来没写时间跨度（2010/2017/2022 会看不出年份），统一补上
SKEL_FIX = ('chart_dynamic', 1,
            'The {{chart}} chart tracks how {{topic}} changed over the period.',
            'The {{chart}} chart tracks how {{topic}} changed from {{time1}} to {{time2}}.',
            '该 {{chart}} 图记录了这一时期 {{topic}} 的变化。',
            '该 {{chart}} 图记录了 {{time1}} 到 {{time2}} 期间 {{topic}} 的变化。')


# 适配表纠错：`items`（事物/类别个数）与 `hint` 与真题原图不符的年份
GUIDE_FIX = {
    '2015': {'items': 4},      # 新年礼物 40 / 聚会吃饭 20 / 交通 20 / 其他 20 → 4 类
    '2018': {'items': 5},      # 特色 36.3 / 服务 26.8 / 环境 23.8 / 价格 8.4 / 其他 4.7 → 5 类
    '2012': {'items': 3},      # 表格：3 个年龄组 × 3 种态度
    '2023': {'hint': '居民健康素养：一条上升线，2016 年后明显加快（先慢后快）'},
    '2026': {'hint': '儿童户外活动益处：满足好奇心 54.6% / 促进观察力 54.5% / 强身健体 33.2% / 增强亲子互动 31.2%'},   # 原写 37.2% 与图不符
}
